/**
 * Сборка итогового Dart-файла из деревьев всех тем.
 *
 * Детерминизм: темы упорядочены по имени, внутри каждой — сортировка эмиттером.
 * Один фиксированный файл (стабильные путь и имя) → корректный diff в MR без сирот.
 */

import { colorValueToDart, DartColorInput } from "./dart/color"
import { emitThemes, ValueRenderer } from "./dart/emit"
import { Tree } from "./tree/tree"

export interface ThemeTree<V> {
  themeName: string
  tree: Tree<V>
}

export interface OutputFile {
  relativePath: string
  fileName: string
  content: string
}

export interface GenerateColorsConfig {
  generateDisclaimer: boolean
  basePath: string
  colorPath: string
  colorFileName: string
  /** Имя публичного корневого класса, напр. "AppColors". */
  rootClassName: string
  /** Тема, доступная без указания (шорткаты корня), напр. "Light". */
  defaultThemeName: string
}

const DISCLAIMER = "// This file is generated by the Snova Flutter exporter. Do not edit by hand."
const IMPORT = "import 'package:flutter/material.dart';"

const renderColor: ValueRenderer<DartColorInput> = (value) => ({ type: "Color", expr: colorValueToDart(value) })

export function generateColors(themes: Array<ThemeTree<DartColorInput>>, config: GenerateColorsConfig): OutputFile {
  const body = emitThemes(config.rootClassName, themes, config.defaultThemeName, renderColor)

  const head = config.generateDisclaimer ? `${DISCLAIMER}\n\n${IMPORT}` : IMPORT
  const content = `${head}\n\n${body}\n`

  return {
    relativePath: `${config.basePath}${config.colorPath}`,
    fileName: `${config.colorFileName}.dart`,
    content,
  }
}
