/**
 * Сборка итогового Dart-файла из деревьев всех тем.
 *
 * Детерминизм: темы упорядочены по имени, внутри каждой — сортировка эмиттером.
 * Один фиксированный файл (стабильные путь и имя) → корректный diff в MR без сирот.
 */

import { colorValueToDart, DartColorInput } from "./dart/color"
import { emitTheme, ValueRenderer } from "./dart/emit"
import { Tree } from "./tree/tree"

export interface ThemeTree<V> {
  themeName: string
  tree: Tree<V>
}

export interface OutputFile {
  relativePath: string
  fileName: string
  content: string
}

export interface GenerateColorsConfig {
  generateDisclaimer: boolean
  basePath: string
  colorPath: string
  colorFileName: string
}

const DISCLAIMER = "// This file is generated by the Snova Flutter exporter. Do not edit by hand."
const IMPORT = "import 'package:flutter/material.dart';"

const renderColor: ValueRenderer<DartColorInput> = (value) => ({ type: "Color", expr: colorValueToDart(value) })

export function generateColors(themes: Array<ThemeTree<DartColorInput>>, config: GenerateColorsConfig): OutputFile {
  const sorted = [...themes].sort((a, b) => (a.themeName < b.themeName ? -1 : a.themeName > b.themeName ? 1 : 0))
  const body = sorted.map((t) => emitTheme(t.themeName, t.tree, renderColor)).join("\n\n")

  const head = config.generateDisclaimer ? `${DISCLAIMER}\n\n${IMPORT}` : IMPORT
  const content = `${head}\n\n${body}\n`

  return {
    relativePath: `${config.basePath}${config.colorPath}`,
    fileName: `${config.colorFileName}.dart`,
    content,
  }
}
